### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JaGeo**
I am proposing to add more information to the readme of BAMresearch. It would be great if every major code contribution could be highlighted and shortly explained in the readme. Currently, it is hardly possible to discover code based on this github repository and also understand how it is related to research performed at BAM. 

 @thilus @pbenner  @joergfunger @ibressler @BAMcvoelker @toqduj

### CODE REVIEW

**Review by joergfunger — COMMENTED** [review]
I guess we are not trying to coordinate what is published on github - as such I'm not sure if I would name the "most important" projects (who is going to make that list on what decision criterion)?

**Comment by JaGeo** [comment]
My suggestion for a rule would be: if it is a code project from BAM and the author adds it via pull request, it will be on the list.

**Review by joergfunger — COMMENTED** [review]
That sounds like a plan. But I think before merging I would suggest setting up at least an initial structure of the repos to be published that can serve as a basis for future merge requests.

**Comment by JaGeo** [comment]
Yes, everyone is very welcome to comment here and mention repos with descriptions that they would like to add to the Readme. I would then add them to the list.

**Pull request closed without merging**
